################################################################################
MLI_FILE		= node_jsonfile.mli
## Name which will be used in -package with ocamlfind
LIB_NAME		= ocaml-node-jsonfile
################################################################################
